### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by poi33**
This is a pull request for #26
But also includes #27 

And will release 3.1.0 if this is approved.

### CODE REVIEW

**Comment by poi33** [comment]
@Bellfalasch any comments or code review would be appreciated.

**Comment by Bellfalasch** [comment]
I like it, so much easier to read the Thymeleaf examples. Are [the fragments updated too](https://github.com/enonic/lib-menu/tree/master/src/main/resources/site/views/fragments/enonic-lib-menu)?

However, I detect breaking changes since new .title replaces .text in breadcrumbs and .title replaces .displayName and .menuName in menu. My plan was to just add .title to the list of properties, not replace anything. You obviously do whatever you like, but the code change here is going to break for everyone using the data directly so then version should be 4.0.0, or you keep the old properties and just send along the bonus property .title =) I'm mostly fan of the second non-breaking solution.

**Comment by poi33** [comment]
Yeah the code is breaking, so I'll include all the properties to make it none breaking. 
For the 4.0.0 release will have to look into the other issues, as they could include other breaking changes.

**Comment by poi33** [comment]
> "You obviously do whatever you like" 

In my opinion any contributor gets a say in this, its an open source project. @Bellfalasch

**Pull request merged**
